#include "prelude.h"

/* Built-in vector types, written in Breezy and compiled into every program.
   They are ordinary classes: escape analysis stack-allocates non-escaping
   locals (no heap/ARC), ARC handles escapes, and calculateDistance is just
   Math.sqrt. Distance precision matches the element type (float for *f, else
   double); equals is exact component-wise comparison. */

static const char VEC2I[] =
	"class Vector2i\n"
	"{\n"
	"	int x;\n"
	"	int y;\n"
	"	Vector2i(int x = 0, int y = 0) { this.x = x; this.y = y; }\n"
	"	bool equals(Vector2i o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	double calculateDistance(Vector2i o)\n"
	"	{\n"
	"		int dx = this.x - o.x;\n"
	"		int dy = this.y - o.y;\n"
	"		return Math.sqrt(dx * dx + dy * dy);\n"
	"	}\n"
	"}\n";

static const char VEC2L[] =
	"class Vector2l\n"
	"{\n"
	"	long x;\n"
	"	long y;\n"
	"	Vector2l(long x = 0L, long y = 0L) { this.x = x; this.y = y; }\n"
	"	bool equals(Vector2l o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	double calculateDistance(Vector2l o)\n"
	"	{\n"
	"		long dx = this.x - o.x;\n"
	"		long dy = this.y - o.y;\n"
	"		return Math.sqrt(dx * dx + dy * dy);\n"
	"	}\n"
	"}\n";

static const char VEC2F[] =
	"class Vector2f\n"
	"{\n"
	"	float x;\n"
	"	float y;\n"
	"	Vector2f(float x = 0.0f, float y = 0.0f) { this.x = x; this.y = y; }\n"
	"	bool equals(Vector2f o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	float calculateDistance(Vector2f o)\n"
	"	{\n"
	"		float dx = this.x - o.x;\n"
	"		float dy = this.y - o.y;\n"
	"		return (float)Math.sqrt(dx * dx + dy * dy);\n"
	"	}\n"
	"}\n";

static const char VEC2D[] =
	"class Vector2d\n"
	"{\n"
	"	double x;\n"
	"	double y;\n"
	"	Vector2d(double x = 0.0, double y = 0.0) { this.x = x; this.y = y; }\n"
	"	bool equals(Vector2d o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	double calculateDistance(Vector2d o)\n"
	"	{\n"
	"		double dx = this.x - o.x;\n"
	"		double dy = this.y - o.y;\n"
	"		return Math.sqrt(dx * dx + dy * dy);\n"
	"	}\n"
	"}\n";

static const char VEC3I[] =
	"class Vector3i\n"
	"{\n"
	"	int x;\n"
	"	int y;\n"
	"	int z;\n"
	"	Vector3i(int x = 0, int y = 0, int z = 0) { this.x = x; this.y = y; this.z = z; }\n"
	"	bool equals(Vector3i o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		if (this.z != o.z) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	double calculateDistance(Vector3i o)\n"
	"	{\n"
	"		int dx = this.x - o.x;\n"
	"		int dy = this.y - o.y;\n"
	"		int dz = this.z - o.z;\n"
	"		return Math.sqrt(dx * dx + dy * dy + dz * dz);\n"
	"	}\n"
	"}\n";

static const char VEC3L[] =
	"class Vector3l\n"
	"{\n"
	"	long x;\n"
	"	long y;\n"
	"	long z;\n"
	"	Vector3l(long x = 0L, long y = 0L, long z = 0L) { this.x = x; this.y = y; this.z = z; }\n"
	"	bool equals(Vector3l o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		if (this.z != o.z) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	double calculateDistance(Vector3l o)\n"
	"	{\n"
	"		long dx = this.x - o.x;\n"
	"		long dy = this.y - o.y;\n"
	"		long dz = this.z - o.z;\n"
	"		return Math.sqrt(dx * dx + dy * dy + dz * dz);\n"
	"	}\n"
	"}\n";

static const char VEC3F[] =
	"class Vector3f\n"
	"{\n"
	"	float x;\n"
	"	float y;\n"
	"	float z;\n"
	"	Vector3f(float x = 0.0f, float y = 0.0f, float z = 0.0f) { this.x = x; this.y = y; this.z = z; }\n"
	"	bool equals(Vector3f o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		if (this.z != o.z) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	float calculateDistance(Vector3f o)\n"
	"	{\n"
	"		float dx = this.x - o.x;\n"
	"		float dy = this.y - o.y;\n"
	"		float dz = this.z - o.z;\n"
	"		return (float)Math.sqrt(dx * dx + dy * dy + dz * dz);\n"
	"	}\n"
	"}\n";

static const char VEC3D[] =
	"class Vector3d\n"
	"{\n"
	"	double x;\n"
	"	double y;\n"
	"	double z;\n"
	"	Vector3d(double x = 0.0, double y = 0.0, double z = 0.0) { this.x = x; this.y = y; this.z = z; }\n"
	"	bool equals(Vector3d o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		if (this.z != o.z) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	double calculateDistance(Vector3d o)\n"
	"	{\n"
	"		double dx = this.x - o.x;\n"
	"		double dy = this.y - o.y;\n"
	"		double dz = this.z - o.z;\n"
	"		return Math.sqrt(dx * dx + dy * dy + dz * dz);\n"
	"	}\n"
	"}\n";

const char *BZY_PRELUDE[] = { VEC2I, VEC2L, VEC2F, VEC2D, VEC3I, VEC3L, VEC3F, VEC3D };
const int   BZY_PRELUDE_COUNT = 8;
