#include "prelude.h"

/* Built-in vector types, written in Breezy and compiled into every program.
   They are ordinary classes: escape analysis stack-allocates non-escaping
   locals (no heap/ARC), ARC handles escapes, and calculateDistance is just
   Math.sqrt. Distance precision matches the element type (float for *f, else
   double); equals is exact component-wise comparison. */

static const char VEC2I[] =
	"class Vector2i\n"
	"{\n"
	"	int x;\n"
	"	int y;\n"
	"	Vector2i(int x = 0, int y = 0) { this.x = x; this.y = y; }\n"
	"	bool equals(Vector2i o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	double calculateDistance(Vector2i o)\n"
	"	{\n"
	"		int dx = this.x - o.x;\n"
	"		int dy = this.y - o.y;\n"
	"		return Math.sqrt(dx * dx + dy * dy);\n"
	"	}\n"
	"}\n";

static const char VEC2L[] =
	"class Vector2l\n"
	"{\n"
	"	long x;\n"
	"	long y;\n"
	"	Vector2l(long x = 0L, long y = 0L) { this.x = x; this.y = y; }\n"
	"	bool equals(Vector2l o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	double calculateDistance(Vector2l o)\n"
	"	{\n"
	"		long dx = this.x - o.x;\n"
	"		long dy = this.y - o.y;\n"
	"		return Math.sqrt(dx * dx + dy * dy);\n"
	"	}\n"
	"}\n";

static const char VEC2F[] =
	"class Vector2f\n"
	"{\n"
	"	float x;\n"
	"	float y;\n"
	"	Vector2f(float x = 0.0f, float y = 0.0f) { this.x = x; this.y = y; }\n"
	"	bool equals(Vector2f o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	float calculateDistance(Vector2f o)\n"
	"	{\n"
	"		float dx = this.x - o.x;\n"
	"		float dy = this.y - o.y;\n"
	"		return (float)Math.sqrt(dx * dx + dy * dy);\n"
	"	}\n"
	"}\n";

static const char VEC2D[] =
	"class Vector2d\n"
	"{\n"
	"	double x;\n"
	"	double y;\n"
	"	Vector2d(double x = 0.0, double y = 0.0) { this.x = x; this.y = y; }\n"
	"	bool equals(Vector2d o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	double calculateDistance(Vector2d o)\n"
	"	{\n"
	"		double dx = this.x - o.x;\n"
	"		double dy = this.y - o.y;\n"
	"		return Math.sqrt(dx * dx + dy * dy);\n"
	"	}\n"
	"}\n";

static const char VEC3I[] =
	"class Vector3i\n"
	"{\n"
	"	int x;\n"
	"	int y;\n"
	"	int z;\n"
	"	Vector3i(int x = 0, int y = 0, int z = 0) { this.x = x; this.y = y; this.z = z; }\n"
	"	bool equals(Vector3i o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		if (this.z != o.z) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	double calculateDistance(Vector3i o)\n"
	"	{\n"
	"		int dx = this.x - o.x;\n"
	"		int dy = this.y - o.y;\n"
	"		int dz = this.z - o.z;\n"
	"		return Math.sqrt(dx * dx + dy * dy + dz * dz);\n"
	"	}\n"
	"}\n";

static const char VEC3L[] =
	"class Vector3l\n"
	"{\n"
	"	long x;\n"
	"	long y;\n"
	"	long z;\n"
	"	Vector3l(long x = 0L, long y = 0L, long z = 0L) { this.x = x; this.y = y; this.z = z; }\n"
	"	bool equals(Vector3l o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		if (this.z != o.z) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	double calculateDistance(Vector3l o)\n"
	"	{\n"
	"		long dx = this.x - o.x;\n"
	"		long dy = this.y - o.y;\n"
	"		long dz = this.z - o.z;\n"
	"		return Math.sqrt(dx * dx + dy * dy + dz * dz);\n"
	"	}\n"
	"}\n";

static const char VEC3F[] =
	"class Vector3f\n"
	"{\n"
	"	float x;\n"
	"	float y;\n"
	"	float z;\n"
	"	Vector3f(float x = 0.0f, float y = 0.0f, float z = 0.0f) { this.x = x; this.y = y; this.z = z; }\n"
	"	bool equals(Vector3f o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		if (this.z != o.z) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	float calculateDistance(Vector3f o)\n"
	"	{\n"
	"		float dx = this.x - o.x;\n"
	"		float dy = this.y - o.y;\n"
	"		float dz = this.z - o.z;\n"
	"		return (float)Math.sqrt(dx * dx + dy * dy + dz * dz);\n"
	"	}\n"
	"}\n";

static const char VEC3D[] =
	"class Vector3d\n"
	"{\n"
	"	double x;\n"
	"	double y;\n"
	"	double z;\n"
	"	Vector3d(double x = 0.0, double y = 0.0, double z = 0.0) { this.x = x; this.y = y; this.z = z; }\n"
	"	bool equals(Vector3d o)\n"
	"	{\n"
	"		if (this.x != o.x) { return false; }\n"
	"		if (this.y != o.y) { return false; }\n"
	"		if (this.z != o.z) { return false; }\n"
	"		return true;\n"
	"	}\n"
	"	double calculateDistance(Vector3d o)\n"
	"	{\n"
	"		double dx = this.x - o.x;\n"
	"		double dy = this.y - o.y;\n"
	"		double dz = this.z - o.z;\n"
	"		return Math.sqrt(dx * dx + dy * dy + dz * dz);\n"
	"	}\n"
	"}\n";

/* DateTime: a mutable date-time object. One field (epoch millis, UTC);
   accessors present local time via bzy_local_offset_secs (runtime/clock.c).
   Civil-date math is a branch-free day<->civil algorithm in Breezy;
   CivilDate/LocalParts exist only to return grouped fields (Breezy has no
   multiple return). Months are 1-based; getDayOfWeek is ISO (1=Mon..7=Sun).
   See documentation/stdlib/datetime.md. */
static const char DATETIME[] =
	"extern long bzy_local_offset_secs(long secs);\n"
	"class CivilDate\n"
	"{\n"
	"	int year;\n"
	"	int month;\n"
	"	int day;\n"
	"	CivilDate(int year, int month, int day)\n"
	"	{\n"
	"		this.year = year;\n"
	"		this.month = month;\n"
	"		this.day = day;\n"
	"	}\n"
	"}\n"
	"class LocalParts\n"
	"{\n"
	"	int year;\n"
	"	int month;\n"
	"	int day;\n"
	"	int hour;\n"
	"	int minute;\n"
	"	int second;\n"
	"	int ms;\n"
	"}\n"
	"class DateTime\n"
	"{\n"
	"	long millis;\n"
	"	DateTime()\n"
	"	{\n"
	"		this.millis = Clock.currentTimeMillis();\n"
	"	}\n"
	"	DateTime(long millis)\n"
	"	{\n"
	"		this.millis = millis;\n"
	"	}\n"
	"	DateTime(int year, int month, int day, int hour = 0, int minute = 0, int second = 0)\n"
	"	{\n"
	"		this.millis = DateTime.fromLocal(year, month, day, hour, minute, second, 0);\n"
	"	}\n"
	"	static long floorDiv(long a, long b)\n"
	"	{\n"
	"		long q = a / b;\n"
	"		if (a % b != 0L)\n"
	"		{\n"
	"			if ((a < 0L) != (b < 0L))\n"
	"			{\n"
	"				q = q - 1L;\n"
	"			}\n"
	"		}\n"
	"		return q;\n"
	"	}\n"
	"	static long floorMod(long a, long b)\n"
	"	{\n"
	"		return a - DateTime.floorDiv(a, b) * b;\n"
	"	}\n"
	"	static bool isLeap(int year)\n"
	"	{\n"
	"		if (year % 4 != 0)\n"
	"		{\n"
	"			return false;\n"
	"		}\n"
	"		if (year % 100 != 0)\n"
	"		{\n"
	"			return true;\n"
	"		}\n"
	"		if (year % 400 != 0)\n"
	"		{\n"
	"			return false;\n"
	"		}\n"
	"		return true;\n"
	"	}\n"
	"	static int daysInMonth(int year, int month)\n"
	"	{\n"
	"		if (month == 2)\n"
	"		{\n"
	"			if (DateTime.isLeap(year))\n"
	"			{\n"
	"				return 29;\n"
	"			}\n"
	"			return 28;\n"
	"		}\n"
	"		if (month == 4 or month == 6 or month == 9 or month == 11)\n"
	"		{\n"
	"			return 30;\n"
	"		}\n"
	"		return 31;\n"
	"	}\n"
	"	static long daysFromCivil(int year, int month, int day)\n"
	"	{\n"
	"		long y = (long) year;\n"
	"		if (month <= 2)\n"
	"		{\n"
	"			y = y - 1L;\n"
	"		}\n"
	"		long era;\n"
	"		if (y >= 0L)\n"
	"		{\n"
	"			era = y / 400L;\n"
	"		}\n"
	"		else\n"
	"		{\n"
	"			era = (y - 399L) / 400L;\n"
	"		}\n"
	"		long yoe = y - era * 400L;\n"
	"		long mp;\n"
	"		if (month > 2)\n"
	"		{\n"
	"			mp = (long) (month - 3);\n"
	"		}\n"
	"		else\n"
	"		{\n"
	"			mp = (long) (month + 9);\n"
	"		}\n"
	"		long doy = (153L * mp + 2L) / 5L + (long) (day - 1);\n"
	"		long doe = yoe * 365L + yoe / 4L - yoe / 100L + doy;\n"
	"		return era * 146097L + doe - 719468L;\n"
	"	}\n"
	"	static CivilDate civilFromDays(long z)\n"
	"	{\n"
	"		long zz = z + 719468L;\n"
	"		long era;\n"
	"		if (zz >= 0L)\n"
	"		{\n"
	"			era = zz / 146097L;\n"
	"		}\n"
	"		else\n"
	"		{\n"
	"			era = (zz - 146096L) / 146097L;\n"
	"		}\n"
	"		long doe = zz - era * 146097L;\n"
	"		long yoe = (doe - doe / 1460L + doe / 36524L - doe / 146096L) / 365L;\n"
	"		long y = yoe + era * 400L;\n"
	"		long doy = doe - (365L * yoe + yoe / 4L - yoe / 100L);\n"
	"		long mp = (5L * doy + 2L) / 153L;\n"
	"		long d = doy - (153L * mp + 2L) / 5L + 1L;\n"
	"		long m;\n"
	"		if (mp < 10L)\n"
	"		{\n"
	"			m = mp + 3L;\n"
	"		}\n"
	"		else\n"
	"		{\n"
	"			m = mp - 9L;\n"
	"		}\n"
	"		long yr = y;\n"
	"		if (m <= 2L)\n"
	"		{\n"
	"			yr = yr + 1L;\n"
	"		}\n"
	"		return new CivilDate((int) yr, (int) m, (int) d);\n"
	"	}\n"
	"	static long fromLocal(int year, int month, int day, int hour, int minute, int second, int ms)\n"
	"	{\n"
	"		long months = (long) year * 12L + (long) (month - 1);\n"
	"		long y = DateTime.floorDiv(months, 12L);\n"
	"		long mo = months - y * 12L + 1L;\n"
	"		long days = DateTime.daysFromCivil((int) y, (int) mo, 1) + (long) (day - 1);\n"
	"		long localSec = days * 86400L + (long) hour * 3600L + (long) minute * 60L + (long) second;\n"
	"		long off = bzy_local_offset_secs(localSec);\n"
	"		long utcSec = localSec - off;\n"
	"		return utcSec * 1000L + (long) ms;\n"
	"	}\n"
	"	LocalParts localParts()\n"
	"	{\n"
	"		long secs = DateTime.floorDiv(this.millis, 1000L);\n"
	"		long localSec = secs + bzy_local_offset_secs(secs);\n"
	"		long days = DateTime.floorDiv(localSec, 86400L);\n"
	"		long sod = localSec - days * 86400L;\n"
	"		CivilDate c = DateTime.civilFromDays(days);\n"
	"		LocalParts p = new LocalParts();\n"
	"		p.year = c.year;\n"
	"		p.month = c.month;\n"
	"		p.day = c.day;\n"
	"		p.hour = (int) (sod / 3600L);\n"
	"		p.minute = (int) ((sod % 3600L) / 60L);\n"
	"		p.second = (int) (sod % 60L);\n"
	"		p.ms = (int) DateTime.floorMod(this.millis, 1000L);\n"
	"		return p;\n"
	"	}\n"
	"	int getYear() { return this.localParts().year; }\n"
	"	int getMonth() { return this.localParts().month; }\n"
	"	int getDay() { return this.localParts().day; }\n"
	"	int getHour() { return this.localParts().hour; }\n"
	"	int getMinute() { return this.localParts().minute; }\n"
	"	int getSecond() { return this.localParts().second; }\n"
	"	int getMillisecond() { return this.localParts().ms; }\n"
	"	long toMillis() { return this.millis; }\n"
	"	int getDayOfWeek()\n"
	"	{\n"
	"		long secs = DateTime.floorDiv(this.millis, 1000L);\n"
	"		long localSec = secs + bzy_local_offset_secs(secs);\n"
	"		long days = DateTime.floorDiv(localSec, 86400L);\n"
	"		return (int) DateTime.floorMod(days + 3L, 7L) + 1;\n"
	"	}\n"
	"	void setYear(int v) { LocalParts p = this.localParts(); this.millis = DateTime.fromLocal(v, p.month, p.day, p.hour, p.minute, p.second, p.ms); }\n"
	"	void setMonth(int v) { LocalParts p = this.localParts(); this.millis = DateTime.fromLocal(p.year, v, p.day, p.hour, p.minute, p.second, p.ms); }\n"
	"	void setDay(int v) { LocalParts p = this.localParts(); this.millis = DateTime.fromLocal(p.year, p.month, v, p.hour, p.minute, p.second, p.ms); }\n"
	"	void setHour(int v) { LocalParts p = this.localParts(); this.millis = DateTime.fromLocal(p.year, p.month, p.day, v, p.minute, p.second, p.ms); }\n"
	"	void setMinute(int v) { LocalParts p = this.localParts(); this.millis = DateTime.fromLocal(p.year, p.month, p.day, p.hour, v, p.second, p.ms); }\n"
	"	void setSecond(int v) { LocalParts p = this.localParts(); this.millis = DateTime.fromLocal(p.year, p.month, p.day, p.hour, p.minute, v, p.ms); }\n"
	"	void setMillisecond(int v) { LocalParts p = this.localParts(); this.millis = DateTime.fromLocal(p.year, p.month, p.day, p.hour, p.minute, p.second, v); }\n"
	"	void addMillis(int n) { this.millis = this.millis + (long) n; }\n"
	"	void addSeconds(int n) { this.millis = this.millis + (long) n * 1000L; }\n"
	"	void addMinutes(int n) { this.millis = this.millis + (long) n * 60000L; }\n"
	"	void addHours(int n) { this.millis = this.millis + (long) n * 3600000L; }\n"
	"	void addDays(int n)\n"
	"	{\n"
	"		LocalParts p = this.localParts();\n"
	"		this.millis = DateTime.fromLocal(p.year, p.month, p.day + n, p.hour, p.minute, p.second, p.ms);\n"
	"	}\n"
	"	void addMonths(int n)\n"
	"	{\n"
	"		LocalParts p = this.localParts();\n"
	"		long months = (long) p.year * 12L + (long) (p.month - 1) + (long) n;\n"
	"		int ny = (int) DateTime.floorDiv(months, 12L);\n"
	"		int nm = (int) (months - (long) ny * 12L) + 1;\n"
	"		int maxd = DateTime.daysInMonth(ny, nm);\n"
	"		int nd = p.day;\n"
	"		if (nd > maxd)\n"
	"		{\n"
	"			nd = maxd;\n"
	"		}\n"
	"		this.millis = DateTime.fromLocal(ny, nm, nd, p.hour, p.minute, p.second, p.ms);\n"
	"	}\n"
	"	void addYears(int n)\n"
	"	{\n"
	"		this.addMonths(n * 12);\n"
	"	}\n"
	"	bool before(DateTime o) { return this.millis < o.millis; }\n"
	"	bool after(DateTime o) { return this.millis > o.millis; }\n"
	"	bool equals(DateTime o) { return this.millis == o.millis; }\n"
	"	string toString() { return Clock.getDateString(this.millis); }\n"
	"	string format(string pattern) { return Clock.getDateString(this.millis, pattern); }\n"
	"}\n";

/* Option<T> and Result<T, E>: built-in generic sum types for "a value or nothing"
   and "a value or an error". Generic enums, so they cost nothing until used. */
static const char OPTION[] =
	"enum Option<T>\n"
	"{\n"
	"	Some(T v),\n"
	"	None;\n"
	"}\n";

static const char RESULT[] =
	"enum Result<T, E>\n"
	"{\n"
	"	Ok(T v),\n"
	"	Err(E e);\n"
	"}\n";

/* Pool<T>: a bounded pool of reusable resources, backed by a buffered channel
   used as a free-list. The constructor opens `size` resources from the factory
   up front; acquire() hands one out (parking the breeze when all are checked
   out), release() returns one. The connection pool is Pool<PgConnection> /
   Pool<MyConnection>; the same class pools any reusable resource. Generic, so it
   costs nothing until instantiated. The factory must be bound to a ()->T variable
   before `new Pool<T>(...)` (a lambda literal is not inferred through a generic
   constructor parameter). See documentation/stdlib/pool.md.
   ponytail: fixed size, no lazy-grow / idle-eviction / validate-on-borrow /
   acquire-timeout / closeAll — each is a measured follow-up, not v1. */
static const char POOL[] =
	"class Pool<T>\n"
	"{\n"
	"	channel<T> free;\n"
	"	Pool(int size, ()->T factory)\n"
	"	{\n"
	"		this.free = new channel<T>(size);\n"
	"		int i = 0;\n"
	"		while (i < size)\n"
	"		{\n"
	"			this.free.send(factory());\n"
	"			i = i + 1;\n"
	"		}\n"
	"	}\n"
	"	T acquire()\n"
	"	{\n"
	"		return this.free.recv();\n"
	"	}\n"
	"	void release(T r)\n"
	"	{\n"
	"		this.free.send(r);\n"
	"	}\n"
	"}\n";

const char *BZY_PRELUDE[] = { VEC2I, VEC2L, VEC2F, VEC2D, VEC3I, VEC3L, VEC3F, VEC3D, DATETIME, OPTION, RESULT, POOL };
const int   BZY_PRELUDE_COUNT = 12;

/* ---- Desktop GUI prelude (Breezy source). ---- */

/* The C entry points implemented in runtime/desktop.c. Marshalled to the GTK
   thread; marked `blocking` so the calling breeze parks instead of stalling a
   scheduler core while the GTK thread services the request. Names match the C
   symbols (bzy_desktop_*); Breezy `long` carries handles, `int`/`bool` are
   32-bit, `string` marshals to char*. */
/* Split across units of <=8 functions each (the per-unit top-level function
   cap), since each prelude string is parsed as one unit. */
static const char DESKTOP_EXTERNS_A[] =
	"extern blocking bool bzy_desktop_is_enabled();\n"
	"extern blocking long bzy_desktop_frame_new();\n"
	"extern blocking long bzy_desktop_frame_content(long frame);\n"
	"extern blocking void bzy_desktop_frame_set_title(long frame, string title);\n"
	"extern blocking long bzy_desktop_panel_new();\n"
	"extern blocking long bzy_desktop_button_new();\n"
	"extern blocking void bzy_desktop_button_set_text(long btn, string text);\n"
	"extern blocking long bzy_desktop_label_new();\n";

static const char DESKTOP_EXTERNS_B[] =
	"extern blocking void bzy_desktop_label_set_text(long lbl, string text);\n"
	"extern blocking void bzy_desktop_container_add(long parent, long child);\n"
	"extern blocking void bzy_desktop_border_add(long border, long child, int region);\n"
	"extern blocking void bzy_desktop_set_visible(long widget, bool visible);\n"
	"extern blocking void bzy_desktop_set_enabled(long widget, bool enabled);\n"
	"extern blocking void bzy_desktop_window_set_size(long window, int w, int h);\n"
	"extern blocking void bzy_desktop_window_show(long window);\n"
	"extern blocking void bzy_desktop_window_dispose(long window);\n";

static const char DESKTOP_EXTERNS_C[] =
	"extern blocking void bzy_desktop_listen_action(long widget, int regIndex);\n"
	"extern blocking void bzy_desktop_listen_window_close(long window, int regIndex);\n"
	"extern blocking int bzy_desktop_next_event();\n"
	"extern blocking int bzy_desktop_event_kind();\n";

static const char DESKTOP_LISTENERS[] =
	"interface ActionListener\n"
	"{\n"
	"	void actionPerformed(ActionEvent e);\n"
	"}\n"
	"interface WindowListener\n"
	"{\n"
	"	void windowClosing(WindowEvent e);\n"
	"}\n";

static const char DESKTOP_EVENTS[] =
	"class ActionEvent\n"
	"{\n"
	"	Component source;\n"
	"	ActionEvent(Component source) { this.source = source; }\n"
	"}\n"
	"class WindowEvent\n"
	"{\n"
	"	Component source;\n"
	"	WindowEvent(Component source) { this.source = source; }\n"
	"}\n";

static const char DESKTOP_BORDERLAYOUT[] =
	"static class BorderLayout\n"
	"{\n"
	"	static int NORTH = 0;\n"
	"	static int SOUTH = 1;\n"
	"	static int WEST = 2;\n"
	"	static int EAST = 3;\n"
	"	static int CENTER = 4;\n"
	"}\n";

static const char DESKTOP_COMPONENT[] =
	"class Component\n"
	"{\n"
	"	long handle;\n"
	"	int regIndex;\n"
	"	void setVisible(bool v) { bzy_desktop_set_visible(this.handle, v); }\n"
	"	void setEnabled(bool v) { bzy_desktop_set_enabled(this.handle, v); }\n"
	"	void dispatch(int kind) { }\n"
	"}\n";

static const char DESKTOP_CONTAINER[] =
	"class Container extends Component\n"
	"{\n"
	"	void add(Component c) { bzy_desktop_container_add(this.handle, c.handle); }\n"
	"}\n";

static const char DESKTOP_WINDOW[] =
	"class Window extends Container\n"
	"{\n"
	"	void setSize(int w, int h) { bzy_desktop_window_set_size(this.handle, w, h); }\n"
	"	void show() { bzy_desktop_window_show(this.handle); }\n"
	"	void dispose() { bzy_desktop_window_dispose(this.handle); }\n"
	"}\n";

static const char DESKTOP_FRAME[] =
	"class Frame extends Window\n"
	"{\n"
	"	long content;\n"
	"	WindowListener winListener;\n"
	"	Frame()\n"
	"	{\n"
	"		this.handle = bzy_desktop_frame_new();\n"
	"		this.content = bzy_desktop_frame_content(this.handle);\n"
	"		this.regIndex = Desktop.register(this);\n"
	"		bzy_desktop_listen_window_close(this.handle, this.regIndex);\n"
	"	}\n"
	"	void setTitle(string t) { bzy_desktop_frame_set_title(this.handle, t); }\n"
	"	void add(Component c) { bzy_desktop_border_add(this.content, c.handle, 4); }\n"
	"	void addRegion(Component c, int region) { bzy_desktop_border_add(this.content, c.handle, region); }\n"
	"	void addWindowListener(WindowListener l) { this.winListener = l; }\n"
	"	void dispatch(int kind)\n"
	"	{\n"
	"		if (kind == 1)\n"
	"		{\n"
	"			if (this.winListener != null)\n"
	"			{\n"
	"				WindowEvent e = new WindowEvent(this);\n"
	"				this.winListener.windowClosing(e);\n"
	"			}\n"
	"		}\n"
	"	}\n"
	"}\n";

static const char DESKTOP_PANEL[] =
	"class Panel extends Container\n"
	"{\n"
	"	Panel() { this.handle = bzy_desktop_panel_new(); }\n"
	"}\n";

static const char DESKTOP_LABEL[] =
	"class Label extends Component\n"
	"{\n"
	"	Label() { this.handle = bzy_desktop_label_new(); }\n"
	"	void setText(string t) { bzy_desktop_label_set_text(this.handle, t); }\n"
	"}\n";

static const char DESKTOP_BUTTON[] =
	"class Button extends Component\n"
	"{\n"
	"	ActionListener listener;\n"
	"	Button()\n"
	"	{\n"
	"		this.handle = bzy_desktop_button_new();\n"
	"		this.regIndex = Desktop.register(this);\n"
	"	}\n"
	"	void setText(string t) { bzy_desktop_button_set_text(this.handle, t); }\n"
	"	void addActionListener(ActionListener l)\n"
	"	{\n"
	"		this.listener = l;\n"
	"		bzy_desktop_listen_action(this.handle, this.regIndex);\n"
	"	}\n"
	"	void dispatch(int kind)\n"
	"	{\n"
	"		if (this.listener != null)\n"
	"		{\n"
	"			ActionEvent e = new ActionEvent(this);\n"
	"			this.listener.actionPerformed(e);\n"
	"		}\n"
	"	}\n"
	"}\n";

/* Desktop: the entry point, the registration table mapping event reg-indices
   back to widget objects, and the run-loop that pulls events and dispatches to
   listeners in Breezy (C never calls back in). */
static const char DESKTOP_CORE[] =
	"static class Desktop\n"
	"{\n"
	"	static Component[] reg = new Component[4096];\n"
	"	static int regCount = 0;\n"
	"	static bool isEnabled()\n"
	"	{\n"
	"		return bzy_desktop_is_enabled();\n"
	"	}\n"
	"	static int register(Component c)\n"
	"	{\n"
	"		int i = Desktop.regCount;\n"
	"		Desktop.reg[i] = c;\n"
	"		Desktop.regCount = i + 1;\n"
	"		return i;\n"
	"	}\n"
	"	static void run()\n"
	"	{\n"
	"		while (true)\n"
	"		{\n"
	"			int idx = bzy_desktop_next_event();\n"
	"			if (idx < 0) { return; }\n"
	"			int kind = bzy_desktop_event_kind();\n"
	"			Component c = Desktop.reg[idx];\n"
	"			c.dispatch(kind);\n"
	"		}\n"
	"	}\n"
	"}\n";

const char *BZY_DESKTOP_PRELUDE[] =
{
	DESKTOP_EXTERNS_A,
	DESKTOP_EXTERNS_B,
	DESKTOP_EXTERNS_C,
	DESKTOP_LISTENERS,
	DESKTOP_EVENTS,
	DESKTOP_BORDERLAYOUT,
	DESKTOP_COMPONENT,
	DESKTOP_CONTAINER,
	DESKTOP_WINDOW,
	DESKTOP_FRAME,
	DESKTOP_PANEL,
	DESKTOP_LABEL,
	DESKTOP_BUTTON,
	DESKTOP_CORE
};
const int BZY_DESKTOP_PRELUDE_COUNT = 14;
